services:
  postgres:
    image: postgres:15-alpine
    container_name: ultron-db
    environment:
      POSTGRES_DB: ultrondb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: devsecret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/src/core/db/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ultron-backend
    environment:
      - PORT=4000
      - DB_HOST=postgres
      - DB_NAME=ultrondb
      - DB_USER=appuser
      - DB_PASSWORD=devsecret
      - JWT_SECRET=ultron_super_secret_jwt_key_2026
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ultron-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  pgdata:
