apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ultron-store-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ultron-store
  source:
    repoURL: https://github.com/Shaun-Trigga96/ULTRON-STORE.git
    targetRevision: main
    path: gitops/helm/ultron-store
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ultron-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
