apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ultron-store-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ultron-store/ultron-ecommerce-platform.git
    targetRevision: HEAD
    path: gitops/helm/ultron-store
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ultron-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
