apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ultron-prod

resources:
  - namespace.yaml
  - datastores.yaml
  - catalog-service.yaml
  - inventory-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - frontend-store.yaml
  - gateway.yaml

commonLabels:
  app.kubernetes.io/part-of: ultron-store
